### ISSUE TITLE
Push notification not working

### ISSUE THREAD

**Issue by ApexInfosysIndia** [home-assistant/home-assistant-android#460]
-->

**1.7.2-2**

**10.0**

**Oppo Reno 2**

**Home Assistant 0.105.5**

**Only works with the official (play store)**

**Push notifications aren't working. All the other features including location tracking, etc. are working fine.**

**Comment by dshokouhi** [comment]
Please try these steps in order: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by ApexInfosysIndia** [comment]
It's still not working...does it have something to do with package name

**Comment by dshokouhi** [comment]
@ApexInfosysIndia can you please let us know all the steps you took.  It sounds like you are setting up your development environment but it is extremely hard to tell because the issue template is very vague.  Please provide us with all necessary info in order to properly help you.

**Comment by JBassett** [comment]
Are you trying to use the push notifications on your own build of the application?  If so that is by design.  In order to get push notifications you need to override https://github.com/home-assistant/home-assistant-android/blob/aacb4ea605c8fd3c59d3b0550c128a47eafdc365/data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt#L41 and setup the full stack: https://github.com/home-assistant/mobile-apps-fcm-push

**Comment by ApexInfosysIndia** [comment]
I'm using the clone of Home Assistant to design a better app interface...for that, I didn't want to mix it with the original app build, therefore I changed the package name...since then, location tracking is working fine but push notification isn't. Also, there are many errors in the original build...so it could be because of that as well...I am confused right now!!

**Comment by JBassett** [comment]
Even if you kept the same package name you wouldn't be able to use the existing infrastructure to send notifications.  If you want to test notifications locally you need to setup https://github.com/home-assistant/mobile-apps-fcm-push for yourself.

**Comment by ApexInfosysIndia** [comment]
Hi @JBassett 

Can you elaborate the process to set up the full stack and what do you mean by overriding  private const val PUSH_URL = "https://mobile-apps.home-assistant.io/api/sendPush/android/v1"

**Comment by JBassett** [comment]
You need to deploy this repository with your own FCM info (https://github.com/home-assistant/mobile-apps-fcm-push).  Then update the PUSH_URL in the application to the url that Google gives your function.  We can't give out the keys needed to use our infrastructure so when you debug locally you need to have your own setup.

**Comment by ApexInfosysIndia** [comment]
Shall I also override all the 3 Push URL in home-assistant-android-1.8.0/data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt @JBassett

**Comment by ApexInfosysIndia** [comment]
Thanks @JBassett It worked!

**Comment by ApexInfosysIndia** [comment]
@JBassett It's only working on one device and one home assistant instance only...?

**Comment by ApexInfosysIndia** [comment]
When I use it for my home instance on my sister's android device, it worked. As soon as I installed it the same apk on my personal device and logged into my office HA instance, the latter stopped getting any notifications...

**Comment by ApexInfosysIndia** [comment]
Is there any kind of delay issue? Cuz we don't face such with the official HA app

**Comment by Nik71git** [comment]
Hi there, maybe the problem is like mine, I've two Redmi Note 5, the app rename the devices in the same way since they're identical, I change the device name in App configuratione and all notifications are working fine; when I do a logout/login from the app then the app rename again the smartpfones with tha same name. This cause app notifications not working. Do you already know about this issue?

**Comment by dshokouhi** [comment]
@Nik71git everytime you rename the device you need to restart HA for the new name to take place.

**Comment by Nik71git** [comment]
Thank you!I’ll follow the fresh installation guide for the app. probably I need to clear app cache too.  Nicola Moretto Da: Daniel ShokouhiInviato: domenica 26 aprile 2020 19:49A: home-assistant/androidCc: Nik71git; MentionOggetto: Re: [home-assistant/android] Push notification not working (#460) @Nik71git everytime you rename the device you need to restart HA for the new name to take place.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Nik71git** [comment]
> @Nik71git everytime you rename the device you need to restart HA for the new name to take place.

I've just try, it works until I do logout from the app, when I login again in the app, the device in the app is named always as original: "Redmi note 5" instead of "nicola". this means all my automations don't work. I rename the device in the app "nicola" and all works fine without restarting HA. App android release 1.8.0-144. It's mandatory to do logout from app because if the device will be stole they can have access to all my devices in HA until I delete them since the theft find the app with login executed.

**Comment by dshokouhi** [comment]
@Nik71git lets not keep commenting on an old issue.  Please open a new issue with all the steps you take.  Keep in mind this may be expected behavior in that every time you log out you need to set the device name again and restart HA.
