### ISSUE TITLE
Notifications going through a thid party server ?

### ISSUE THREAD

**Issue by Ulrar** [home-assistant/home-assistant-android#481]
Hi,

While trying to push notifications to my phone I just noticed this in my logs :

```Timeout sending notification to https://mobile-apps.home-assistant.io/api/sendPushNotification```

Does this mean that when pushing notifications to my phone, they're actually being pushed through some third party server ? Is that essential for the android notifications to work ? Since I'm not receiving anything on my phone I'm assuming yes.

I may have missed it, but I don't see any mentions it in the documentation (apart from the 150 limit mentioned in troubleshooting which hints at it), that really ought to be mentioned in my opinion.

Thanks

**Comment by robbiet480** [comment]
It is mentioned a few times [here](https://companion.home-assistant.io/docs/notifications/notification-details). Yes, they are being passed through our (the Home Assistant project) server. Notifications can not be sent directly from your Home Assistant to Firebase to your device because we can't share the required API keys with the world. If we did that, everyone could be spammed. It's the same architecture as the iOS app.

**Comment by robbiet480** [comment]
Also, please update your Android app version. That URL is old and only used for the iOS app as of right now.
