### ISSUE TITLE
Nothing happens when I enter address manually

### ISSUE THREAD

**Issue by ofalvai** [home-assistant/home-assistant-android#51]
This might be related to #50, but I can't connect to HA manually either. Nothing happens when I press the OK button after I entered my HA instance's address.

**Comment by escoand** [comment]
Additionally the address field should be a single line and a hit on the `enter` key should try connect.

**Comment by balloob** [comment]
What address are you entering @ofalvai ? Do you include the protocol and exclude the path?

@escoand that is off-topic of this issue, create a new issue

**Comment by ofalvai** [comment]
You are right, I forgot to include the protocol part. I think I'll submit a
PR that adds an example address to the input placeholder, and some
validation as well.

**Comment by RussNelson** [comment]
When I enter http://10.0.1.7:8123 I get a blank screen (it should at least say "attempting to connect"). After about a minute, I get
`Webpage not available

The webpage at http://10.0.1.7:8123/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback could not be loaded because:

net::ERROR_CONNECTION_TIMED_OUT`

**Comment by wacher74** [comment]
Exactly same.
Nothing happens when I enter address manually just a blank, white page.
Autoscan found nothing.
-- 
my solution: my HA has valid Let's Encrypt SSL to my ddns-net name, I tried to connect via local (192...) address. Certification was not valid, I think. Maybe a warning would be useful.

**Comment by balloob** [comment]
This feature has been added.
