### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by marklester** [home-assistant/home-assistant-android#80]
Hello, I would like to be able to install this on my nvidia shield.
Regards,

**Comment by Knoxie** [comment]
Just curious what the benefits of the app vs just viewing using shield web browser?

**Comment by marklester** [comment]
I would imagine same reason for the app. You don't have to navigate to a page and you can use native widgets for the various ui components.

**Comment by neopilou** [comment]
Add this in AndroidManifest.XML :
![2020-01-16_11h45_49](https://user-images.githubusercontent.com/45233613/72518641-12160f80-3856-11ea-9a2b-794b12f990a5.png)

And add "ic_banner.png" (320x180) in /app/src/main/res/mipmap-xhdmi
![2020-01-16_11h47_31](https://user-images.githubusercontent.com/45233613/72518821-64573080-3856-11ea-9028-14102a418e4b.png)


That's all, build your apk, and install it on your android tv (nvidia shield or xiaomi)...

The controls (right, left, up, down for example) cannot be managed in the application, but only in the HASS interface (because it is content displayed in a webview, I think, but maybe i'm wrong)

**Comment by JBassett** [comment]
@neopilou since it looks like you have already done the work, mind creating a PR for this?

**Comment by neopilou** [comment]
PR added ([#264](https://github.com/home-assistant/home-assistant-android/pull/264))

**Comment by JBassett** [comment]
Added with https://github.com/home-assistant/home-assistant-android/pull/264

**Comment by stbeep1** [comment]
> Added with #264

When will HA support for android tv officially? Do you have a timeline about that ? Thank you:)
